import React, { forwardRef } from 'react';
import { useTripContext } from '../context/TripContext';

const ExpenseReceipt = forwardRef((props, ref) => {
  const { tripName, members, expenses, totalSpent } = useTripContext();
  const perPerson = members.length > 0 ? (totalSpent / members.length) : 0;

  return (
    <div ref={ref} style={{
      width: '400px',
      padding: '30px',
      background: '#0A0F1E',
      color: '#F0F0F0',
      fontFamily: 'sans-serif',
      border: '4px solid #781728',
      position: 'absolute',
      left: '-9999px',
      top: 0
    }}>
      <h2 style={{ color: '#F0F0F0', borderBottom: '2px solid #4F0715', paddingBottom: '10px', textAlign: 'center', marginBottom: '20px' }}>
        {tripName} Expense Report
      </h2>
      
      <div style={{ marginBottom: '30px' }}>
        <h3 style={{ color: '#781728', marginBottom: '10px' }}>Expenses List</h3>
        {expenses.map(e => (
          <div key={e.id} style={{ display: 'flex', justifyContent: 'space-between', margin: '8px 0', borderBottom: '1px dashed #333' }}>
            <span>{e.description} <span style={{fontSize: '0.8rem', color: '#7A8499'}}>({e.category})</span></span>
            <span style={{ fontWeight: 'bold' }}>₹{e.amount}</span>
          </div>
        ))}
        {expenses.length === 0 && <div style={{color: '#7A8499'}}>No expenses logged.</div>}
        
        <div style={{ background: '#4F0715', padding: '10px', marginTop: '10px', borderRadius: '5px', display: 'flex', justifyContent: 'space-between', fontWeight: 'bold' }}>
          <span>Total Spent:</span>
          <span>₹{totalSpent}</span>
        </div>
      </div>
      
      <div>
        <h3 style={{ color: '#781728', marginBottom: '10px' }}>Settlements</h3>
        <p style={{ fontSize: '0.9rem', color: '#F0F0F0', marginBottom: '15px' }}>Per person share: <b style={{color: '#D4AF37'}}>₹{perPerson.toFixed(2)}</b></p>
        
        {members.map(m => {
          const balance = m.amount - perPerson;
          const statusText = balance > 0 
            ? `Gets back ₹${Math.abs(balance).toFixed(2)}` 
            : `Owes ₹${Math.abs(balance).toFixed(2)}`;
          const statusColor = balance >= 0 ? '#4CAF50' : '#FF4757';
          
          return (
            <div key={m.id} style={{ margin: '10px 0', border: '1px solid rgba(255,255,255,0.1)', background: 'rgba(255,255,255,0.02)', padding: '15px', borderRadius: '8px' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '5px' }}>
                <span style={{ fontWeight: 'bold', fontSize: '1.1rem' }}>{m.name}</span>
                <span style={{ color: statusColor, fontWeight: 'bold' }}>{statusText}</span>
              </div>
              <div style={{ fontSize: '0.9rem', color: '#7A8499' }}>Total Paid: ₹{m.amount}</div>
            </div>
          );
        })}
        {members.length === 0 && <div style={{color: '#7A8499'}}>No members added.</div>}
      </div>
      
      <div style={{ textAlign: 'center', marginTop: '40px', fontSize: '0.8rem', color: '#7A8499' }}>
        Generated by Wanderwise Trip Planner
      </div>
    </div>
  );
});

export default ExpenseReceipt;
